### ISSUE TITLE
Add SSL in Cassandra Query task to support AWS Amazon Keyspaces

### ISSUE THREAD

**Issue by vKrypto** [kestra-io/plugin-cassandra#44]
## context: I am trying to get data from Cassandra (aws keyspace) using kestra.

For Astradb we have a secure connection way:
```
id: "query"
type: "io.kestra.plugin.astradb.Query"
session:
  secureBundle: /path/to/secureBundle.zip
  keyspace: astradb_keyspace
  clientId: astradb_clientId
  clientSecret: astradb_clientSecret
cql: SELECT * FROM CQL_TABLE
fetch: true
```

but for cassandra we don't have it, anything like secure-connection/ssl etc.:
```
id: "query"
type: "io.kestra.plugin.cassandra.Query"
session:
  endpoints:
    - hostname: localhost
  username: cassandra_user
  password: cassandra_passwd
cql: SELECT * FROM CQL_KEYSPACE.CQL_TABLE
fetch: true
```
it would really help if we could get something like SSL to enable secure mode connection.

right now we are not able to connect aws keyspace(Cassandra) using "io.kestra.plugin.cassandra.Query"

Thanks
